### ISSUE TITLE
issue in distance_type.tpp

### ISSUE THREAD

**Issue by lwt831** [ipc-sim/ipc-toolkit#1]
The return value of point_triangle_distance_type is incorrect. 

For example: p =[0.488166 0.0132623  0.289055]; v0 = [0.456476 0.0526442  0.260834]; v1 = [0.609111 0.0595969  0.275928]; v2 = [0.431262 0.0508414  0.255831].

**Comment by zfergus** [comment]
Hi, thank you for pointing this issue out. I replaced the incorrect `point_triangle_distance_type` with the one used in the original IPC code. I also added some extra tests for the function. Let me know if there are any further problems.

**Comment by lwt831** [comment]
It's cool!

BTW, I guess that assert(....toi <= 0) in lines 806, 830 and 853 of ipc.cpp should be changed to assert(...toi <= 1). Is that correct?

**Comment by zfergus** [comment]
Yes, you are right. I will push a fixed version.
