### ISSUE TITLE
std::array issue

### ISSUE THREAD

**Issue by csyzzkdcz** [ipc-sim/ipc-toolkit#10]
I use your codes as suggested. But encountered with error: implicit instantiation of undefined template 'std::array<long, 4>' for collision_constraint.hpp. 

Fix: add #include<array> inside the collision_constraint.hpp.

**Comment by zfergus** [comment]
Yes, thank you I just had the same compilation error. Will push the fix in a bit.

**Comment by zfergus** [comment]
Fixed 😄
