### ISSUE TITLE
Segfault on Python versions >=3.9

### ISSUE THREAD

**Issue by elkalt** [ipc-sim/ipc-toolkit#102]
**Describe the bug**
CollisionMesh constructor segfaults on Python versions >=3.9.

**To Reproduce**
I used pyenv to get python versions 3.8.19 and 3.9.19 and ran the same test file (below) with both.  Python 3.8.19 raised no errors while 3.9.19 gave a segfault.

```python
from numpy import array
import ipctk

points = array([[-0.5, 0.5], [0.5, 0.5], [0.5, -0.5]])
edges = array([[0, 1], [1, 2], [2, 0]])
faces = array([[0, 1, 2]])

mesh = ipctk.CollisionMesh(points, edges, faces)
```

**Environment:**
 Tested on both Debian Sid and macOS Monterey 12.2.1 with both raising the same issue

**Additional context**
I haven't tested any other functions, but I assume that there might be other issues as well.

**Comment by zfergus** [comment]
I installed Python3.9 and got the same segmentation fault 😞. I will try to determine the issue, but for now, I would recommend using a different Python version if possible.

**Comment by elkalt** [comment]
I installed the toolkit using pip, and I'm using the latest version there (1.2 I believe).  I was originally trying to use it with Python 3.12 on Debian and had the segfault as well (which I forgot to mention in the original post, sorry).  I just retested with both Python 3.11.7 and 3.11.9 and got hit a segfault with both, so it might be somewhat platform dependent.

**Comment by zfergus** [comment]
Hmm, how strange. I will try to reproduce this on my end.

**Comment by zfergus** [comment]
I may have figured it out. It looks like the version of Pybind11 I am currently using (2.11.1) is incompatible with Numpy 2.0. I updated my Numpy to 2.0 and got a segfault with Python 3.11.

I plan to update Pybind11 in #100 which should fix the problem in `main`. I'll think about how to best address this in a way that fixes the Pypi installation, but for now, `ipctk v1.2` is only compatible with `numpy<2`

**Comment by zfergus** [comment]
You can now install v1.2.1 with [pip](https://pypi.org/project/ipctk/1.2.1/) which contains a patch fix to use the latest pybind11. This should fix your issue without requiring you to update to our latest API.
