### ISSUE TITLE
CollisionMesh Python constructor requires faces array in 2D

### ISSUE THREAD

**Issue by elkalt** [ipc-sim/ipc-toolkit#103]
**Describe the bug**
Faces array is required in the CollisionMesh Python constructor even in 2D.

**To Reproduce**
The short script below raises the following TypeError.  Modifiying the constructor to take `array([[0, 1, 2]])` as the face parameter runs normally, even without modifying the points to have an additional z coordinate.
```python
from numpy import array
import ipctk

points = array([[-0.5, 0.5], [0.5, 0.5], [0.5, -0.5]])
edges = array([[0, 1], [1, 2], [2, 0]])

mesh = ipctk.CollisionMesh(points, edges)
```
```
Traceback (most recent call last):
  File "./test.py", line 7, in <module>
    mesh = ipctk.CollisionMesh(points, edges)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. ipctk.CollisionMesh(rest_positions: numpy.ndarray[numpy.float64[m, n]], edges: numpy.ndarray[numpy.int32[m, n]], faces: numpy.ndarray[numpy.int32[m, n]], displacement_map: scipy.sparse.csc_matrix[numpy.float64] = <0x0 sparse matrix of type '<class 'numpy.float64'>'
        with 0 stored elements in Compressed Sparse Column format>)
    2. ipctk.CollisionMesh(include_vertex: List[bool], full_rest_positions: numpy.ndarray[numpy.float64[m, n]], edges: numpy.ndarray[numpy.int32[m, n]], faces: numpy.ndarray[numpy.int32[m, n]], displacement_map: scipy.sparse.csc_matrix[numpy.float64] = <0x0 sparse matrix of type '<class 'numpy.float64'>'
        with 0 stored elements in Compressed Sparse Column format>)

Invoked with: array([[-0.5,  0.5],
       [ 0.5,  0.5],
       [ 0.5, -0.5]]), array([[0, 1],
       [1, 2],
       [2, 0]])
```
**Expected behavior**
The Getting Started tutorial has a note that mentions that `In 2D only the edges matrix is required. In 3D both edges and faces are required.`, however, this is not reflected in the behaviour.

**Environment (please complete the following information):**
 - OS and Version: Debian Sid
 - Compiler and Version: Python 3.8.19

**Comment by zfergus** [comment]
Thank you for bringing this to my attention. You are correct the face matrix is currently required even for 2D. I will try to fix this. For now you can pass an empty array (`array([])`) as input for the face matrix and it will work.
