### ISSUE TITLE
Python module 'ipctk' has no attribute 'Collision'

### ISSUE THREAD

**Issue by elkalt** [ipc-sim/ipc-toolkit#104]
**Describe the bug**
Trying to call the Collisions constructor in Python raises an AttributeError `module 'ipctk' has no attribute 'Collision'`.

**To Reproduce**
Call the Collisions constructor, ie. `collisions = ipctk.Collisions()`.

**Environment (please complete the following information):**
 - OS: Debian Sid
 - Version: IPCTK 1.2
 - Python version: Python 3.8.19

**Comment by zfergus** [comment]
`Collisions` is called `CollisionConstraints` in v1.2. I think you might be looking at the latest documentation while using version 1.2. Here are the docs to v1.2: https://ipctk.xyz/v1.2.0/tutorial/getting_started.html.

**Comment by elkalt** [comment]
That's correct - thanks for pointing me in the right direction :)
