### ISSUE TITLE
Tutorial uses dhat rather than BarrierPotential in FrictionCollisions().build() (1.3.0)

### ISSUE THREAD

**Issue by elkalt** [ipc-sim/ipc-toolkit#126]
The tutorial for 1.3.0 contains this code:
```python
friction_collisions = ipctk.FrictionCollisions()
friction_collisions.build(
    collision_mesh, vertices, collisions, dhat, barrier_stiffness, mu)
````
But this fails as it expects a BarrierPotential rather than dhat.

**Comment by zfergus** [comment]
Thank you for pointing this out. I fixed the `main` tutorial. It used to be able to implicitly cast between `double` and `BarrierPotential`, but I removed this feature (marked constructor `explicit`).
