### ISSUE TITLE
EdgeEdgeConstraint distance gradient crash

### ISSUE THREAD

**Issue by tytrusty** [ipc-sim/ipc-toolkit#16]
The method `EdgeEdgeConstraint::compute_distance_gradient` calls `edge_edge_distance_gradient` with `VectorMax9d` as its output, and I'm hitting an Eigen runtime size assert. Shouldn't this vector be `VectorMax12d`? Switching to `VectorMax12d` fixes it on my end, but I wanted to make sure. 

If this is an unexpected bug I can post more details, thanks :)

**Comment by zfergus** [comment]
Yes, you are right. I just fixed this in the latest commit on main.

Thank you for pointing this out.
