### ISSUE TITLE
Shallow checkout with FetchContent may fail if tag is not HEAD

### ISSUE THREAD

**Issue by Andlon** [ipc-sim/ipc-toolkit#35]
The suggested `CMakeLists.txt` configuration to fetch `ipc-toolkit` automatically is:

```
include(FetchContent)
FetchContent_Declare(
    ipc_toolkit
    GIT_REPOSITORY https://github.com/ipc-sim/ipc-toolkit.git
    GIT_TAG ${IPC_TOOLKIT_GIT_TAG}
    GIT_SHALLOW TRUE
)
FetchContent_MakeAvailable(ipc_toolkit)
```
However, this appears to only work reliably if `GIT_TAG` is set to a commit that corresponds to `HEAD` or possibly some other branch. For example, right now `HEAD` is `51cf348b50939913fa8f101845e7c55ac98c62f4`, for which it works. However, if I set `${IPC_TOOLKIT_GIT_TAG}` to `c8bc2a1c13fa2c4627fc9a20c8e4bf02e5215164`, which is one commit behind `HEAD`, then I get the following error:

```
-- The CXX compiler identification is GNU 11.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
[ 11%] Creating directories for 'ipc_toolkit-populate'
[ 22%] Performing download step (git clone) for 'ipc_toolkit-populate'
Cloning into 'ipc_toolkit-src'...
fatal: reference is not a tree: c8bc2a1c13fa2c4627fc9a20c8e4bf02e5215164
CMake Error at ipc_toolkit-subbuild/ipc_toolkit-populate-prefix/tmp/ipc_toolkit-populate-gitclone.cmake:40 (message):
  Failed to checkout tag: 'c8bc2a1c13fa2c4627fc9a20c8e4bf02e5215164'


gmake[2]: *** [CMakeFiles/ipc_toolkit-populate.dir/build.make:102: ipc_toolkit-populate-prefix/src/ipc_toolkit-populate-stamp/ipc_toolkit-populate-download] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/ipc_toolkit-populate.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

CMake Error at /usr/share/cmake-3.22/Modules/FetchContent.cmake:1087 (message):
  Build step for ipc_toolkit failed: 2
Call Stack (most recent call first):
  /usr/share/cmake-3.22/Modules/FetchContent.cmake:1216:EVAL:2 (__FetchContent_directPopulate)
  /usr/share/cmake-3.22/Modules/FetchContent.cmake:1216 (cmake_language)
  /usr/share/cmake-3.22/Modules/FetchContent.cmake:1259 (FetchContent_Populate)
  CMakeLists.txt:16 (FetchContent_MakeAvailable)


-- Configuring incomplete, errors occurred!
```

Similarly with older commits. It looks as if this might be a [bug in cmake](https://gitlab.kitware.com/cmake/cmake/-/issues/23379), related to the shallow clone functionality. Indeed, if I set `GIT_SHALLOW FALSE` it works also with other commits.

I'm not sure how to resolve this issue - since it appears to be a bug in `cmake`, perhaps just add a note in the documentation that it may be necessary to disable shallow cloning if you want to pin the toolkit to a particular commit? (which I guess you usually want to do in order to ensure that your build doesn't suddenly fail due to upstream changes)

**Comment by zfergus** [comment]
This is a working example that we use in PolyFEM: https://github.com/polyfem/polyfem/blob/main/cmake/recipes/ipc_toolkit.cmake

**Comment by Andlon** [comment]
Ah, thanks for the clarification, that was not obvious to me!

**Comment by zfergus** [comment]
Updated the documentations.
