### ISSUE TITLE
Average body mass in IPC-toolkit vs average lumped nodal mass in IPC

### ISSUE THREAD

**Issue by halehOssadat** [ipc-sim/ipc-toolkit#49]
I have a question about the arguments in adaptive barrier stiffness function called `ipc::initial_barrier_stiffness`, it has one argument called `const double average_mass` which indicates as average mass of all bodies while in `IPC` function called `suggestKappa(kappa)` and according to Supplement of IPC paper, it should be average of lumped nodal mass. Does it the same as `IPC`?
And what types of CCD `IPC-toolkit` does use for `ipc::compute_collision_free_stepsize`, it seems that it is `TIGHT_INCLUSION` while it seems that `IPC` uses `FLOATING_POINT_ROOT_FINDER` as default. Can I use this with `IPC-toolkit`?

**Comment by zfergus** [comment]
The `average_mass` indeed refers to the "average lumped nodal mass" as described in the supplemental document of our original IPC paper. 

By default, the IPC Toolkit uses the [Tight-Inclusion](https://github.com/Continuous-Collision-Detection/Tight-Inclusion) CCD algorithm. To use the same CCD as in the original IPC codebase you can set the CMake option `IPC_TOOLKIT_WITH_CORRECT_CCD` to `OFF`.

**Comment by halehOssadat** [comment]
Thanks for your clarification, I assume that `ipc::compute_collision_free_stepsize` doesn't compute the `CFL-INSPIRED CULLING OF CCD`. I also want to implement this part using `IPC-toolkit`, but I am not sure what is the equivalent functions for `sh.build(result, searchDir, alpha, result.avgEdgeLen / 3.0);` and what is the best way to do it using `IPC-toolkit`?

**Comment by zfergus** [comment]
I added the CFL-inspired culling of CCD in PR #50. I will merge it in once I test it. Feel free to use the branch if you want to try it out.

**Comment by zfergus** [comment]
See [this](https://github.com/ipc-sim/ipc-toolkit/blob/main/tests/test_cfl.cpp) file for example usage.
