### ISSUE TITLE
Basic example of initialization and simulation loop

### ISSUE THREAD

**Issue by DamianoOriti** [ipc-sim/ipc-toolkit#5]
Hi, first of all, thank you for sharing this implementation of IPC.
Would it be possible to have a complete example showing the initialization of deformable bodies and the simulation loop?
Is there any documentation on how to use this toolkit?

**Comment by zfergus** [comment]
Hi, yes I plan to add more documentation/examples for how to use the library and its functions. 

However, it seems like you are asking how to build a full simulator using the toolkit. If this is the case, then the toolkit is not all that is needed. The toolkit only contains the components necessary for collision detection and response (including friction). It does not contain the specific code for simulating deformable bodies. For this, I would point you to our original [IPC codebase](https://github.com/ipc-sim/ipc) which includes a full deformable simulator, or to the more general [PolyFEM](https://polyfem.github.io/) which uses this toolkit for handling collisions.

Let me know if I misunderstood your questions.
