### ISSUE TITLE
CCD high memory usage (bad allocation)

### ISSUE THREAD

**Issue by Q-Minh** [ipc-sim/ipc-toolkit#99]
Hi,

Firstly, thank you for making IPC available to us all! I tried integrating IPC Toolkit (version `1.2.0`) in a Python elastic simulation script, and thought to try it on a simple example first to check that it works. The example is basically 2 beam models, one fixed on the bottom, and another one, free falling from the top. I'm using a basic Newton PCG loop and the beam models are pretty coarse, and the example is not very contact rich, especially compared to what I know IPC is able to achieve. However, the CCD step (`ipctk.compute_collision_free_stepsize`) hogs up crazy amounts of memory on my 64GB of RAM desktop, and the program crashes after a `bad allocation` exception.

Here is [the code](https://gist.github.com/Q-Minh/6d29e5f76297a37d1750e11bde7e9fac#file-ipc_ccd_high_mem-py). I provide the beam mesh model that I am using, and a `requirements.txt` file to install all versioned Python dependencies that I am using locally. You can run the script and get the `polyscope` GUI showing the example scenario. I know the script might not be the "minimum" reproducible code snippet, but I find that it is helpful to have the visuals without modification to the code and to reproduce my setup exactly. I am using Python 3.12.

I also unit scale the models, so the CCD trajectories should not be that long, not too sure what is consuming so much memory. I hope you find the time to investigate this issue. This might just be a misunderstanding about how to use the IPC Toolkit correctly too.

Thank you!

**Comment by zfergus** [comment]
Hello,

Thank you for using the toolkit and providing detailed instructions and code to reproduce the error. 

I have a couple of suggestions for you to try out before I dive into your code:

1. If you enable the logger (`ipctk.set_logger_level(ipctk.LoggerLevel.trace)`), the broad phase should print the average edge length and displacement length along with the number of voxels being used. You can share this to help us debug.
2. This error is known to happen for the default broad phase (`HashGrid` as well as `SpatialHash`) when the trajectory length is large (relative to the scene size). Try to use a different broad-phase method. For example,
```python
max_step_size = ipctk.compute_collision_free_stepsize(
    collision_mesh, vertices_t0, vertices_t1,
    broad_phase_method=ipctk.BroadPhaseMethod.BOUNDING_VOLUME_HIERARCHY)
```
or you can try `ipctk.BroadPhaseMethod.SWEEP_AND_TINIEST_QUEUE` (renamed to `ipctk.BroadPhaseMethod.SWEEP_AND_PRUNE` in main).

Let me know how these affect your results.

Best,
Zach

**Comment by Q-Minh** [comment]
Thanks for the quick reply! Great suggestion, should've tried that before. I get the following output
```
[2024-07-11 13:47:43.281] [ipctk] [trace] suggesting voxel size of 0.7760268607404458 (avg_edge_len=0.38773843035834854)
[2024-07-11 13:47:43.282] [ipctk] [trace] hash-grid resized with a size of 2x2x1
[2024-07-11 13:47:44.088] [ipctk] [trace] suggesting voxel size of nan (avg_edge_len=nan avg_disp_len=nan)
[2024-07-11 13:47:44.088] [ipctk] [trace] hash-grid resized with a size of 1x1x1
```
The `nan` values actually come from the barrier gradients `gradB = cconstraints.compute_potential_gradient(cmesh, X, dhat)`.

**Comment by zfergus** [comment]
That is interesting. Maybe we are hitting a corner case that was not checked before (i.e., what happens if the trajectory is nan).

As for why the gradient is NaN, I believe this can only occur if the mesh is interesting. Can you confirm wether there are intersections when evaluating the gradient? You can use the following to check:
```
is_intersecting = ipctk.has_intersections(collision_mesh, vertices)
```

**Comment by Q-Minh** [comment]
Yes, the mesh is apparently intersecting from that call! But I'm fairly sure that it is not (at least geometrically), from what I'm rendering. I'll try to do some more investigation on my side to figure out why I'm seemingly not starting from an intersection-free state.

**Comment by zfergus** [comment]
A useful debug tool for this is MeshLab (`Filters > Selection > Select Self Intersecting Faces`). That should help you visualize where there might be self-intersectons.

**Comment by Q-Minh** [comment]
Okay, I will try that. I would be quite surprised if there were self intersections, given that my tetrahedral mesh comes from TetWild, and the `CollisionMesh` is built from `igl.boundary_facets` and `ipctk.edges`.

**Comment by danielepanozzo** [comment]
The boundary of a tetrahedral mesh created by TetWild after the winding number filtering might be self-intersecting at vertices. This is likely the cause, we had it happen before. You should be able to see this in mesh lab.

**Comment by Q-Minh** [comment]
MeshLab apparently does not detect any self intersections, unless I'm not using it correctly (not quite familiar with MeshLab). 
![image](https://github.com/ipc-sim/ipc-toolkit/assets/34039469/3305d2a7-d167-4df6-b39b-baac07d45576)

**Comment by Q-Minh** [comment]
I also verified with libigl that the mesh is edge manifold, and has no boundary edges (i.e. is closed).

**Comment by zfergus** [comment]
Thank you for checking those. From looking at your code, I have one idea of what might be going on.

You have variables `X/V` which are the vertex positions of your tet mesh and `C` which are the tetrahedral elements as an index matrix into `X/V`. 

You then get the boundary faces `F = igl.boundary_facets(C)` and the edges of the boundary faces as `E = ipctk.edges(F)`.

You construct a collision mesh as `cmesh = ipctk.CollisionMesh.build_from_full_mesh(V, E, F)`. This is correct because `V` is the full mesh's vertex positions (i.e., includes internal nodes) and E/F index into the full vertices. 

However, later you do 
```python
cconstraints.build(cmesh, X, dhat, dmin=dmin)
gradB = cconstraints.compute_potential_gradient(cmesh, X, dhat)
gradB = cmesh.to_full_dof(gradB)
```
but every method in the toolkit expects the input vertices will be only the surface vertices. I think this is the problem. Instead what you should be doing is
```python
boundary_X = cmesh.vertices(X)
cconstraints.build(cmesh, boundary_X, dhat, dmin=dmin)
gradB = cconstraints.compute_potential_gradient(cmesh, boundary_X, dhat)
gradB = cmesh.to_full_dof(gradB)
```

Try making this change (and changing other instances where you use `X` instead of `boundary_X`) and see if that causes your issue.

**Comment by zfergus** [comment]
P.S. this bug would be caught if you run in debug mode (i.e, `assert(vertices.rows() == mesh.num_vertices());`), but the Python bindings compile in release (i.e., no asserts) by default.

**Comment by Q-Minh** [comment]
Oh, I see! I didn't realize that. So for friction, I should also feed in the velocities of the boundary mesh's vertices, then?

**Comment by zfergus** [comment]
Yes, you can do `boundary_velocities = cmesh.map_displacements(full_velocities)`.

**Comment by Q-Minh** [comment]
Okay, I understand, thanks so much for looking into this. I guess that IPC Toolkit's whole API is based on handling purely collision geometry, and the displacement map is only relevant to compute derivatives. Do we have access to the selection matrix, or can I only map row-wise 3-dimensional quantities (positions, velocities, etc.) from the physics mesh to the collision mesh?

**Comment by zfergus** [comment]
Yes, the whole API is based on handling purely collision geometry (I will make this clearer in the [tutorial](https://ipctk.xyz/tutorial/simulation.html).) 

The CollisionMesh has two private fields 
1. `m_displacement_map` which is a sparse matrix such that `collision_displacements = m_displacement_map * full_displacements` where "displacements" can be any quantity/dimension such that there is one row per vertex.
2. `m_displacement_dof_map` which is a sparse matrix such that `collision_dof = m_displacement_dof_map * full_dof` where "dof" can be any quantity as long as there is only one column and each vertex maps to `dimension` (e.g., 2 or 3) rows (in succession).

Unfortunately, I do not expose these variables. Is there a scenario where you would find these matrices useful?

---

Here are the definitions of `vertices`, `displace_vertices`, and `map_displacements` for context

```c++
Eigen::MatrixXd
CollisionMesh::vertices(const Eigen::MatrixXd& full_positions) const
{
    // full_U = full_V - full_V_rest
    assert(full_positions.rows() == full_num_vertices());
    assert(full_positions.cols() == dim());
    return displace_vertices(full_positions - m_full_rest_positions);
}

Eigen::MatrixXd CollisionMesh::displace_vertices(
    const Eigen::MatrixXd& full_displacements) const
{
    // V_rest + S * T * full_U; m_displacement_map = S * T
    return m_rest_positions + map_displacements(full_displacements);
}

Eigen::MatrixXd CollisionMesh::map_displacements(
    const Eigen::MatrixXd& full_displacements) const
{
    assert(m_displacement_map.cols() == full_displacements.rows());
    assert(full_displacements.cols() == dim());
    return m_displacement_map * full_displacements;
}
```

**Comment by Q-Minh** [comment]
Hi Zachary, 

As of now, I can't think of a scenario where I need the selection matrices, but `map_displacements` should be sufficient anyways, so there is probably no need to expose them.

Your fixes have worked for me, although I do have remaining questions that I will probably ask in another issue soon, but they are potentially more so related to IPC, as opposed to the software. Not sure if this is the right communication channel, or you are willing to discuss those.

Thanks for everything!

**Comment by zfergus** [comment]
I am glad we could find a solution to your issue. I am happy to answer any questions you have in the future. If they are more like discussions of the IPC method rather than issues with the software, you can consider using the Discussions tab here on GitHub, but either way is fine.
